### PR TITLE
Fix exception when lastRowId is `undefined`

### PR DESCRIPTION
**Pull request by Fabb111**
- [x] I have verified my changes didn't break the `example` project.

#### Description
lastRowId can be undefined when using a custom primary key, which in turn results in an exception here (Cannot convert undefined to a BigInt)

### CODE REVIEW

**Comment by aidenwallis** [comment]
Is this a duplicate of https://github.com/aidenwallis/kysely-d1/pull/8

**Comment by Fabb111** [comment]
> Is this a duplicate of #8

Yes it is, I saw it after creating the PR. But the fix in my PR is safer as only null and undefined will be „ignored“ and the approach in the other PR could also ignore 0 as value. As this property is not documented I thought I would use the least intrusive variant

**Comment by aidenwallis** [comment]
My bigger concern is the lack of a strict equality check here, can you refactor this to use strict equality checks?

**Comment by Fabb111** [comment]
> My bigger concern is the lack of a strict equality check here, can you refactor this to use strict equality checks?

This is intended, as the non strict equality check also includes `undefined` when checking for null.

**Comment by aidenwallis** [comment]
I would like to refrain from removing strict equality checks in this codebase and will likely add a linting rule to enforce it long term.

Please refactor it if possible!

**Comment by aidenwallis** [comment]
This issue ended up being fixed in #8 - and covers the edge case of `0` that you were concerned about! I'm going to close this PR but feel free to open up an issue or another PR if these changes don't work for you.

Thanks for taking your time to contribute!

**Pull request closed without merging**
